# # Použij oficiální nginx image
# FROM nginx:alpine

# # Smaž výchozí konfiguraci Nginx
# RUN rm -rf /usr/share/nginx/html/*

# # Zkopíruj build výstup do Nginx root složky
# COPY dist /usr/share/nginx/html

# # (volitelné) Vlastní nginx.conf pokud potřebuješ routing
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

# Stage 1 – build React/Vite
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2 – serve přes nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

