# Použij oficiální nginx image
FROM nginx:alpine

# Smaž výchozí konfiguraci Nginx
RUN rm -rf /usr/share/nginx/html/*

# Zkopíruj build výstup do Nginx root složky
COPY dist /usr/share/nginx/html

# (volitelné) Vlastní nginx.conf pokud potřebuješ routing
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
